### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TEbinger** [GreenXenith/skinmaker#2]
It's a pretty cool mod and we tried it on our server Minetestbildung. 
Unfortunately we had server crashs. Maybe You can fix this?

2021-07-22 21:31:03: ERROR[Server]: In thread 7fa4671e5700:
2021-07-22 21:31:03: ERROR[Server]: /tmp/tmp.ZikZG5zMEO/minetest/src/script/cpp_api/s_base.cpp:89: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (not enough memory)

**Comment by GreenXenith** [comment]
@TEbinger can you consistently reproduce this? If so, when exactly does it happen?

**Comment by TEbinger** [comment]
Our server has lots of memory (126 GB), so this can't be the problem. Because it's a used server I don't want to try it again if You didn't change something in the code. Maybe I can make a test when nobody is online ...

**Comment by GreenXenith** [comment]
You misunderstand; I can't help you unless you can reproduce the error consistently. It's not a Lua error so I don't even know if it's my mod causing it. You didn't even tell me when it happens.

**Comment by GreenXenith** [comment]
No response, closing.
